name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  webserv-tests:
    strategy:
      fail-fast: true

    name: cpp project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: check lint cpp files
        run: |
          set -e
          cppcheck --error-exitcode=1 --enable=all --suppress=missingInclude --quiet .
        working-directory: src

      - name: check lint hpp files
        run: |
          set -e
          find . -type f -name "*.hpp" -exec cppcheck --error-exitcode=1 --enable=all --suppress=missingInclude --quiet {} \;
        working-directory: inc

      - name: build
        run: |
          make re

      - name: run tests
        run: |
          make re
          chmod +x .github/ubuntu_tester
          ./.github/ubuntu_tester

      - name: run cgi tests
        run: |
          make re
          chmod +x .github/ubuntu_tester
          ./.github/ubuntu_tester

      - name: check and install python
        run: |
          if ! command -v python3 &> /dev/null || [ $(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))') != "3.10" ]; then
            sudo apt-get update
            sudo apt-get install -y python3
          fi
          if [ -f ".github/py_tests/requirements.txt" ]; then
            pip3 install -r requirements.txt
          fi
        working-directory: .github/py_tests

      - name: run py tests
        run: |
          python3 .github/tests.py
